export const PATH_NAME = {
    HOME: "/",
    ABOUTUS: "/about-us",
    OURCOMMIT: "/our-commit",
    PRIVACYPOLICY: "/privacy-policy",
    ORDERINSTRUCTIONS: "/order-instructions",
    CONTACTINSTRUCTIONS: "/contact-instructions",
    OPERATINGPOLICY: "/operating-policy",
    MENU: "/menu",
    SELLER_REGISTER: "/register/seller",
    CUSTOMER_REGISTER: "/register",
    // ORDER_TRACKING: "/order-tracking",
    DETAILS: "/details",
    DETAIL_ACCOUNT: "/detail-account",
    BLOG: "/blog",
    BLOG_DETAIL: (_id: string) => `/blog/${_id}`,
    CREATE_BLOG: "/blog/create",

    RESTAURANT_DASHBOARD: "/v2/dashboard/restaurant",
    ADMIN_MANAGEACCOUNT: "/v2/dashboard/admin/account",
    // OTPCODE: "/otp-code",
    CHANGEPASSWORD: "/change-password",
}
